#+TITLE:Literate notes for Reverse Engineering Yoda Stories
#+AUTHOR:Archenoth
#+EMAIL:archenoth@gmail.com
:SETTINGS:
#+STARTUP: hidestars inlineimages
#+DRAWERS: SETTINGS
#+PROPERTY: header-args :exports both :eval never-export
#+PROPERTY: header-args:lisp :tangle yes :results silent
:END:

As mentioned in the [[./README.org][README]] These are the literate notes I took while following along [[http://www.zachtronics.com/yoda-stories/][Zachtronics' blog post]] about reverse engineering a binary files.

The post details a game known as "Yoda Stories", and includes a [[http://www.zachtronics.com/yoda-stories/assets/img/YODESK.DTA][binary file download]] to follow along what he does to reverse engineer it.

In this file, I basically follow along with the post, and implement the ideas in Common Lisp, while also paraphrasing both what he describes, as well as the things I guessed and tried to go ahead what I read. (Spoiler alert: That pretty much never worked)

* The overall mentality of reverse engineering a file
So, turns out the first thing you want to do when reverse engineering a binary data file is to figure out how to "skip" data...

When you first open a file, you can bash your head against every single thing you don't understand until you get somewhere, but it's apparently much more fruitful to try and get an overall idea about how to navigate the file itself.

Why can you assume there's even a way to skip data? Because it sounds like usually people don't want to scan through a file for delimiters to navigate to portions of a file.

We can use this to our advantage!

So the first thing we likely need to write code for is to handle the data types we'll be encountering:
#+BEGIN_SRC lisp
  ;; Data types
#+END_SRC

Since we're trying to figure out the *overall* structure, some basic data structure handling is good enough for our purposes here.

In the case of Yoda Stories, it looks like there's a large number of sections in the binary file that are delimited with four-letter uppercase /strings/ of text known as "Tags".

Since we need to read strings, I wrote a function to extract those from a stream in Lisp:
#+BEGIN_SRC lisp :padline no
  (defun read-string (stream length)
    "Reads a string from the passed in stream of the specified length"
    (let ((str (loop for i upto (1- length)
                     collect (read-byte stream))))
      (format nil "窿磲疸狎＇泔溴汨狎篝颟┅＋盼倪右令箝钽桢徜弪狎汨狎徙翦蝮祜铉＋屡巧芜右扉箴ㄤ彐躅蝈徜桢徜弪篝蝈犴⒁遽潴箦泗轱桢徜弪喘汨狎徙翦祜铉篝蜷铉溴铒糸铉箦泗轱镦翳轶忾钺蝙骘蝽狒蝈徜篝蜷铉篝蝈犴穿＋盼倪右物翳狒麇汜蝈徜翳屙轭涕箴麒弪狎濯翳弩翎珞篚痧矬邃麸忮亠汜桴铘秕轭溟鲩漉犰翎珞轭桢邃轸矧怩汨犷沐狎翳狒翳弪狎麽麸箅轲狎秕钿翳骈戾箫秕滹瞌铄邃麸箴邈殒殂犰禊筱犷骘翳轭珞翳狒蝈箦礅戾骘躜篚怏羼蹂铘躔疱蜚狍戾趑弪蟓箝钽翳狒躅蝈扉徕戾犷洮扉脲礤铘轱铄遽蜢殄颥轭彐骈汩孱舢语栾滹麇滹翳轶蕊麸麇骈珲蝈翳轶秕舢歪忮翳弪狎箫礤栝铘轭翳骈蝮箦泗轱羁街乓咏澡街乓咏桢徜弪轶骘祆秣邃怡桨鞍鞍鞍浆麒殂麇汜轭驽轶鲥蝮轱铛礅弪镦箫礤篝戾鏖翳扉脲禊遽汨溟玳镳痫箝翦箝溴镦翳溴汩磲痫轭艉＋屡巧芜咆镣刑刀吹挡党鞍安鞍鞍峙矣＋盼倪咆镣刑语轭翳轶汜箦翳轶轶扉脲禊鲥蝮轱讲敖镦翳轶骈戾骘蝽狒澡轶轶箜犰孱秕玷翳狒翳弪麇蝈瞌犷疳螋殂蹯狎栝铘麸箅轲翳轭珞珏铄蜥祆怩轸汜犰箫忮狍篚礤麸忮珲狎犷翦邃麸忮翳轶箝瀹令麽箝钽翳轶礤犷麇ъ麽铘麸蝈徜铛礅弪蟋黩雉翳轶麸屮趄徙铛礅弪骝镯翳篝蝈犴＋屡巧芜右扉箴ㄤ彐躅蝈徜铛礅弪篝蝈犴脲戾铉翳穿ㄥ钿獒红轸綮瀛孱溟犷┅⒁遽潴铛礅弪骝镯翳疳篌邃轭篝蝈犴溴驷蹯趔麸怡翦犷红轸綮瀛孱溟犷怩翳矬汜忮汨犷珏麸衡殓孱溟犷矧犷铛礅弪镦怡翦螈戾舄è铛眢祜镳骘躔麸ū戾铉翳泔祆邈蝈徜怡翦篝蝈犴┅铛眢ㄩㄥ孱溟犷衡殓孱溟犷蝈鲥蝮铛眢铛眢┅祜镳骘铛轭铛眢犷骝镯篚眄轭ㄡ箬铛í椹┅┅＋盼倪右澡轶轶徙趱犰禊翳骈钺鲥蝮轱镦翳骢钽糸镱忮汜躞骘躅翳狒盹篝铛礅弪麽轭翦蝈篝邃轭麇蝈扉趑戾孱溟犷犷犰箫怡翦祜铉怩翳轶骈蝮轭篝犷沐轭鲲祧邃赭忾绛孱溟犷铛礅弪螽馏轭翳桨安轶讲交鏖翳翳铛礅弪铒蝈泔蜾邃忉汶麽蜾轭翳忾钺蝙语鏖翳翳轶骢钽糸镱＋屡巧芜右扉箴ㄤ彐躅蝈徜鲥蝮轱篝蝈犴⒁遽潴鲥蝮轱铛礅弪骝镯翳疳篌邃轭篝蝈犴ǐ蝈徜铛礅弪篝蝈犴红孱玺哄钿獒衡殓孱溟犷ǒ蝈徜铛礅弪篝蝈犴红孱玺哄钿獒衡殓孱溟犷卑鞍癌┅＋盼倪右令翳狒轸骘翳鲥蝮轱睢项麽蜾麸翳铄箦泗轱瞵犷痫篌殁禊骈珲蜷铉秕栾麸箅轲轸接哉薪礤狍躜轭溽翎犷忮镱洹澡轶翎箫躅潴忾扉脲Ⅲ弭躔怩栳鲥铒殇遽麒狒翳狒礤犷轭翳轶泔铘屮衄箫栾滹弩翳痫篝筢麇溴犰鏖翳翳轶澡犷篦弪轶麸箅轲轸ㄏ镨族蝈骈钺祆珏趑轭麸翳箅轲痖铉怩箝铄篌婶篚珑弩趔麸礤狍躜翳箝镦翳溽翎忮赭邋桢蝈犷翳铄翎绗麒殂轶箫礤翳轭彭徙螫桢汜瞌滹箫黩雉翳轶骢钽糸镱麸桢祓鏖翳翳狒＋屡巧芜右屙徙蟓扉箴ㄤ彐躅桢飙礤狍躜瀛蝈玳镱ī⑼遽篚蝈栾灬蜱翳徙糸鲥蝈玳镱轶ㄩ铘弪徙糸鲥ㄩ蝈玳镱徙糸鲥皓筢鲥屮沲蝮轱戾è痫轭ㄨ屮飙沲蝌孱舡徜潋弩螬┅ㄥ汨犷珏痫轭舡犷洵磲螂戾è溟骀ㄡ怏ō痫轭ㄨ屮飙沲蝌孱舡徜潋弩螬┅┅ㄥ汨犷珏痫轭舡犷洵磲螂礤篌徵⒁犷珏轶ヤ怡翦òグ给溟骀溟骀┅┅礤篌徵⒚躜蝈铘徜潋弩蠛傍グ给ㄨ屮飙沲蝌孱舡徜潋弩螬┅＋盼倪右婶铒弩疱汩犰禊篝屐灬泔溴怩轸麽顼镤孱秕玷麸桢祓鏖翳睐骘祆秣轭犰镱鏖翳卺汨趄镱殂篝蹑娈语驽屐骝邋麸篝遽轸殒秕麽铘麸躞桢麸礤狍躜疳螋镦忾钺蜷弩令麒铿礤狍躜轭翳箝镦翳溽翎蝈鲥犰邃铛礅弪篚箴殂轱躞禊箝黹灬麸翳怡翦轫礤溟狒屐骘祆秣轭翳接哉薪翎绠琉疳蝈铘禊翳轶轶泔眄镱孱秕玷疳趑弪轭忾钺蝙骈戾螽娘轭轸徵衢鏖翳翳铄翎蝈鲥犰邃翳狒翳铄箦泗轱泔蹯犰箫忮箅轲疱扉脲翳轶翳弪濮疳趑弪桢蝈娱钽秕Ⅲ腴痧轭纰轶徙趱犰禊顼轭麸牾篝泔祆邈翳溽翎麇滹瞌躅溴蝮翎钿弭轭麸篝蝓泗躜瀣翳铄翳轭麇铄邃麸滹轶黩轸骢钽糸镱翳狒鏖祆蝈徜溽翎犷蝈趱蝾轸箴邈殒殂犰禊犰箫麸痱镧蝈篌翳骈戾痫轭翦蚝＋屡巧芜右扉箴ㄤ彐躅蝈徜溽翎篝蝈犴戾铉翳⒁遽潴铛礅弪镦怡翦轭麸扉篝矧躅糸哄镦祜镳骘躔麸ū戾铉翳骘怡翦蝈徜怡翦篝蝈犴铋哄镦泔祆邈怡翦┅＋盼倪右组翳翳轶骢钽糸镱麇汜骈钺祆趄犷疳蝮祜镦翳骈戾鏖翳翳轶溴驷蹯篝戾澡狒礤犷蟋麇蝈顼铑篝狎溟篌邈糸铉翳骘蝽狒轸箦戽＋屡巧芜右扉箴换骑蝽狒溟篌邈糸镱＋盼倪右娱钽麇蝈黠螂轭鏖翳溴驷蹯翳狒黹玷怛犷汨骘疳螋殂蹯狎豉疱镦翎绗驽祠扉脲瘐祆轭秕锰嫌鏖翳翳箫戾瘐蝠矬镦磲腴铉轸溟箴狒汨麸礤翳镤骘溟骀弪孱桢徜弪蠛＋屡巧芜右扉箴吼徜扉铄铒ㄤ彐珏铄蜷疳蝮瀛箦泗轱豉疱篝蝈犴ê滹沲礤铘狒轱⒁遽潴箦泗轱犷蝈趱蝾涕篝溴筱蜷忾铉轸┅＋盼倪右澡轶礤犷麇铄邃麸黩轸溟箴狒汨弪翳狒泔铞弪趔遽汨翎麸涕箴脲黠蜾箫遽汨礤翳镤轶遽簌麸箴邈獒扉鏖翳藉耢溴骈铋糸镱蠛＋屡巧芜右扉箴ㄤ彐躅疳蝮瀛篝蝈犴箦泗轱篝蝈犴⒁遽潴篝蝈犴桢徜弪骝镯翳疳篌邃轭篝蝈犴犷溟箴狒汨弩轸麸翳泔蝌邈蝈徜弪礤翳镤疳蝮瀛箦泗轱ㄩ铘弪蝈徜桢徜弪篝蝈犴弘妁黠蜾篝蝈犴┅＋盼倪右令躞轭翳轶麇汜蝈疱狒邃禊汜祆翳轶骢钽糸镱镱翳骈戾篝蝈犴麸痱镧蝈篌轸＋屡巧芜右扉箴ㄤ彐躅疳蝮瀛镤弩é镳糸镱犰ㄦ殪①夏庞水脑立┅⑿狎箦翳傧呐铀脑溽翎骈戾鏖翳镳孱骈戾篝蝈犴骈戾哄戾礤铘豉疱Ж躅箝珙邃怡翦俯祜镳骘疳蝮邃疳蝮瀛篝蝈犴箦泗轱篝蝈犴泔祆邈疳蝮邃躅糸ㄥ哄钿ㄦ轵篝疳蝮邃┅┅＋盼倪右湘泔躜箦骘翳轶麸徙趱犰禊黠螂麇铄邃麸黩轸秕溴驷蹯疳蝮轭礤翳镤麒殂滹弩翳轶疳趑弪麇筢遽蜢殄颦麒弪翳骈蝮怡翦狎犷镦骟弭麸箅轲麸翳铄箦泗轱詈＋屡巧芜右扉箴换腻驷蹯驷祆忉汶ㄤ彐礤翳镤疳蝮瀛箦泗轱豉疱篝蝈犴⑷犷潇轭翳珏铄蜥箦泗轱篝戾戾舄è戾铉翳蝈徜铛礅弪篝蝈犴┅ㄤ狒蝈徜溽翎篝蝈犴戾铉翳┅扉篝豉疱红孱玺戾铉翳轰狒溽翎┅＋盼倪右澡殇遽轶麸蝈徜翳戾铉翳蝈徜翳狒犴秕铘镦溽翎箬秭轸轭麸痨轶衄犷蝈趱蝾轸娱钽麇犰蝈徜腩秣翳狒街乓咏黠螂溟骀弪孱綮翳犷翳轶溴驷蹯衄麇汜黩轸箴邈獒扉狒轱骘翳狒麸锖＋屡巧芜右扉箴换皱蝮轱ㄤ彐礤翳镤疳蝮瀛箦泗轱è豉疱ㄥ耢忽弪螬篝蝈犴⑷犷潇轭翳鲥蝮轱睥扉篝豉疱红孱玺轰狒蝈徜鲥蝮轱篝蝈犴┅＋盼倪右阴铑轭翳金狎箦靳镤弩虢骢钽糸镱黠螂铋沐禊躅糸麇栝翳节衔沤箦泗轱町澡轶礤犷翳轶鏖祆痱镡徕禊忮溟骀弪孱锰嫌箴邈獒扉狒轱瞵狍篚黹铉麇汜骈珲蝈秕栾麸箅轲轸阻殂趱蝾秕麸忮扉趑戾盹蝈轭鲲祧邃清趑轭轭麸翳节衔沤则轭麸箅轲翳蝻蹒翳节衔沤箦泗轱扉脲麇躞踽祆滹牾眇躞轭麸翳黹滗戾镦铒麒弪瀹语麒狒汜麇箦狒翳篝狎糸铉节衔沤＋屡巧芜右扉箴换陲铄＋盼倪右田镫轭狒翳箦泗轱箬秣怩钽镦缴谙谓翎珞犷礤狍躜轭翳溟篝犷沐忮赭邋翳节衔沤犷翳骈蝮缴谙谓翎滹弩瞌祜镫扉脲犷疳螋殂蹯狎禊箴邈獒铛礅弪翳狒汜忮骘躅轭翳忾钺蝙溽翎狎秕钿轸语麒狒秕狃痱镝汨桢蝈蕊滹麇箅轲秭弪节衔沤怎蝾秕衄麇牾篝殓铒蝈轸骘铒鳌歪忮殒麇祜镫狒翳缴谙谓溽翎盹蝈蝈戾鲠铘轭骘蝽狒轱鏖祆痱弩孱轸箦戽伶翦犰缴谙谓箫躅潴扉脲⑸铘弪钺陲铄矧箫礤雉桢痫篌殁禊蝈灬翦溽翎箫戾臾牾篝滹翳狒语麇牾篝栳蜾泔溴箅轲骘翳铛礅弪镦怡翦忮赭邋翳节衔沤犷骈蝮缴谙谓翳孱蝈趄秕礤狍躜轭篝蜥翦琦骘翳箴徙忮赭邋翳骈蝮赭缴谙谓箦泗轱铙麒殂蝈鲥犰铛礅弪翳狒鲥蝙沆矬麸麒狒蝈泔蜾邃驽怡翦忮骘蝈翳缴谙谓翎轸箦戽田镫扉脲翳躅腩秣怡翦狎犰蝈徜篝狎糸铉麸痫篌殁禊忮泔礤腩秣睢语轭蝈鲥蝮孱玳铄弪轭绗沆矬濯徙趱犰禊礤犷箫礤翳轭纭令麇汜躞翳狒麸牾篝狍篚礤翳狒翳轶铛礅弪轶轭溴邃翳戾铉翳溽翎麇蝈祜镫轭骘鏖翳箫礤镦骟弭镦轸秣町藻篝轭翳轶狍篚眇糸镱趱蝾秕殒麇礤狍躜翳铄缴谙谓翳戾铉翳铛礅弪轶犰箫镦怡翳筢礤铛礅弪麻铉锂澡轶祜镫痱镯轶轭轭溴邃语躞轭翳轶麇汜黩轸骢钽糸镱麸疳蝮翳弩缴谙谓箦泗轱铙忉箦镱麒狒麇腩秣令滹瞌舂族犰箫驷泗矧轭翳铛礅弪翳狒翳箝轶镦怡麒殂狃疱狎麸痫篌殁禊忮箝眇禊翳铛礅弪镦怡翦镦翳雉桢躅腩秣溽翎轭沆蹁邃骘遽汨蝈泔蜾＋屡巧芜右扉箴吼徜扉铄铒ㄤ彐躅疳蝮瀛辁镱篝蝈犴⑿狎箦箝铉戾哨衔箦泗轱睥戾舄è铒殇遽蝈徜铛礅弪篝蝈犴红孱玺博戾铉翳蝈徜铛礅弪篝蝈犴红孱玺博铒殇遽蝈徜铛礅弪篝蝈犴┅ㄨ遽溴蝈徜桢徜弪篝蝈犴┅ㄤ狒蝈徜溽翎篝蝈犴ō戾铉翳订┅扉篝ㄩ铘弪桢徜弪弘妁黠蜾轰狒扉篝侯锃殇遽ㄣ镱铒殇遽铒殇遽博轰狒溽翎┅┅＋盼倪右语箫礤翳轭翳狒忮泔礤狃疳蝈铘麒孱蝓铑轭翳轶骢钽糸镱镱翳篝蝈犴蝈疱狒邃禊轶翳狒翳铛礅弪镦缴谙谓箦泗轱铙轭翳骈戾轶翳筢礤狍翳铛礅弪蜷玷徭翦翳节衔沤磲螂弪惋蝈躅腩秣怡翦滹黝犷麇汜犰箫翦祆缴谙谓磲螂弪狎轭溴邃铄篝邃狍篚箴邈翦洹深驷泗翳轶轶孱秕玷麸黩轸锰嫌箴邈獒扉狒轱骘节衔沤翳狒躞弩秕缴谙谓泔溴犷箅轲秭弪翳屙犰臁＋屡巧芜右扉箴ㄤ彐礤翳镤疳蝮瀛箦泗轱è豉疱ㄥ耢胡镱濠篝蝈犴⑷犷潇弩翳堍谙闻堍箦泗轱镦翳忾钺蝙骈戾麒殂轭沆蹁弩怩钽镦铄篝邃哨衔螈戾舄è镱瀛泔躅蝈徜铛礅弪篝蝈犴红孱玺博ㄩ镱弩祜镳骘躔麸ū镱瀛泔躅舂泔祆邈疳蝮瀛辁镱篝蝈犴┅┅扉篝豉疱轰狒辁镱弩┅＋盼倪右伶翦黩轸轭翳轶殒麇蝓秕痱弼轱躞金狎箦镤弩虢骢钽糸镱轸趱蝾秕翳弪濮铒盹蝈泔眇灬轭趔族汜骈钺祆疳蝮翳孱糸蝈骈戾＋屡巧芜右扉箴呼犷珈铒磲疸狎＇汜疳蝮瀛镤弩氅＋盼倪右＋遗诱淘雍褐乓河哉河文涸商黑衔盒遮好攘好茸好琳涸瘟号文砒趄徙糸铉身徵弩澡铄疳螋镦翳痫篝礤铘轱铄翳狒翳狒镱镦翳磲觑顼犰麽麸屮趄徙轫徵弩犷翳狒皆商沤箫躅潴篚箴殂轱躞禊扉脲轫徵弩语祜镫轭狒翳陨膛箦泗轱瞵麇箦祜趔镦忾趔翳狒箦屙麸磲脲痱弭豉箬狃弩轭翳桢邃轸矧阻殂轸溴翎殪翳狒翳弩痖邈弩镦溽翎狎扉脲禊忾繇狃蟆蚤礤麸怩篝秕节形墙犷黩轸箫礤轫徵骈戾蟆＋屡巧芜右扉箴换身徵弩耢厚蹰汶祜徜胡痤绌＋盼倪右弱铘轭狎秕钿翳弪箦屙麸忮铒箝弩怩轸祜镫扉脲翳弪濮卑泊怡翦蟋骘祆秣邃怡怡翦镦轭翦蝽轶箝镱泔蹯漕磲脲桢徜矧翎殪镦翳轶怩徙泔蜾轭麸翳痫篝犰翳糸戾狎巢巢麒殂箦屙扉脲翳蜷玷铛礅弪镦怡翦螽澡狒礤犷麇汜黩轸翳轭翳狒蝈徜卑泊怡翦镦溽翎犷翳孱箴轸秕形呛＋屡巧芜右扉箴呼犷珈铒ㄤ彐躅黩轸瀛痤糸戾溽翎钺礤脲鏖漪巢ㄨ彘玷巢┅⒆蜷翦犷轭溟鲩漉犰形骈戾玳鲥糸戾溽翎犷骈戾钺礤鏖翳镳孱骈戾秕钺礤轰轵邈糸镱猴豸瘐洪姝屮轶趔后躔弪箦溴哄戾礤铘豉疱Ж躅箝珙邃怡翦俯戾è痤磲脲轭篝犷沐痤绾痖屐篝蝈犴邃痤瑚殇翳鏖漪鸿彘玷桢殓梏┅痤绾篝狎舡痤痤秕舂祜镳骘痖屐轭糸戾溽翎滹痤绾黩轸瀛痖屐扉篝痖屐痖屐痖屐痤绌痤绾骈铋箬痤痤绌┅＋盼倪右令翳孱箫礤翳轭翳狒疳蝮弩遽汨汨躅氍犷瘐箬弩轸翳蝻蹒翳徕秭骢钽糸镱＋屡巧芜右扉箴呼犷珈铒ㄤ彐躅黩轸瀛痤珞糸戾溽翎脲ㄩ磲珏箝瀛怡翦卑泊ㄦ灬珞穿⑿狎箦糸戾溽翎轭麸箜犰戾轫徵弩犷黩轸弩翳屙徙泔蜾轭麸栾忾翳溽翎轶轭轫徵瀛箝瀛怡翦犷骒徵螈戾è蝈悱箝ǐ轫徵瀛箝瀛怡翦骒徵螬┅祜镳骘轫徵躔麸ūǒ戾铉翳糸戾溽翎蝈悱箝濠骘篝狎ǐ骒徵í蝈悱箝轫徵濠骘溽翎篚怏羼糸戾溽翎篝狎ǐ篝狎轫徵瀛箝瀛怡翦螬骘骈戾钺礤ㄦ矧磲铋㈤礴轫琬廉痤纰轫徵濠滹黩轸瀛痤溽翎骈戾钺礤┅┅＋盼倪右令翳蝈篚祠轶顼镤澡蝈篚祠轭轫徵骈戾狎铒狒犰翳蜷玷泔祜蝮镡鲩秕箪┈怩翳箬狃弩轭翳屙狎镡鲩秕箪狎衄弩疱汩犰禊灬翦镱麒孱箦犰腴钿镦珧妁筱犰潋镩潴犷篝蹑娈蔑祜蝮迈栾翳桢汶滹麇珏泔祜蝮零泔蜾轭麸翳痫篝翳轶扉脲禊礤犷翳狒翳弪轶疳戾趑箫礤麒弪濉语镳孱邃翳骈戾轭巧托犷躞邃泔祜痖汶弪麸骈钿翳桢鲠祯弩骘驽轭翦蝈篝轭箴蜷翦犷祜镫邃骘翳屙轭翳忾钺蝙骈戾项汜鲥狒栳麸忮汜蝈骢鏖翳麽翳狒翳箴蜷翦镱翳忪镧痫篝箦屙邃麸忮溟翳弪邃箫泔蹯漕珲狎犷翦翳狒翳泔祜蝮麇蝈徙沲蜥翦箫溟漕躞翳狒箝溴麸祜镫骘泔祜蝮牾篝翳桢鲠祯弩轭翳骈戾箴狒秕舢趄殄驽溟骀弪孱篝戾镦泔祜骘蝽狒犷弼孱趱犰禊玑鲥躔犷脲痿蝈徜轭绠怎蝾秕衄栳翳蜷玷殇遽怩翳疳戾趑麽轭翳咆骈戾麒殂麽箢轭沆蹁邃骘顼镤蝈狍镱轫徵轭瀹巷痼忉箝汜祆牾篝泔痖邃翳疳戾趑骝镯翳痫篝犷磲泸铵轸轭麸涕箴鲥泗矧＋屡巧芜右扉箴呼犷珈疳戾趑瀹扉箴ㄤ彐泔铙翎铘辛烫旁（ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ破ｘ破ｘ嘎ｘ鞍ｘ贸ｘ闷ｘ绰ｘ鞍ｘ嘎ｘ脸ｘ甭ｘ鞍ｘ捣ｘ贩ｘ鞍ｘ鞍ｘ嘎ｘ脸ｘ甭ｘ鞍ｘ贸ｘ闷ｘ绰ｘ鞍ｘ坡ｘ坡ｘ坡ｘ鞍ｘ怕ｘ欧ｘ欧ｘ鞍ｘ穆ｘ某ｘ某ｘ鞍ｘ寐ｘ贸ｘ贸ｘ鞍ｘ侣ｘ鲁ｘ鲁ｘ鞍ｘ谅ｘ脸ｘ脸ｘ鞍ｘ孤ｘ钙ｘ钙ｘ鞍ｘ嘎ｘ菲ｘ菲ｘ鞍ｘ仿ｘ镀ｘ镀ｘ鞍ｘ斗ｘ德ｘ德ｘ鞍ｘ捣ｘ绰ｘ绰ｘ鞍ｘ捶ｘ陈ｘ陈ｘ鞍ｘ吵ｘ猜ｘ猜ｘ鞍ｘ渤ｘ甭ｘ甭ｘ鞍ｘ背ｘ捌ｘ捌ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ梅ｘ闯ｘ鞍ｘ鞍ｘ路ｘ闯ｘ鞍ｘ鞍ｘ谅ｘ称ｘ鞍ｘ鞍ｘ蛊ｘ称ｘ鞍ｘ鞍ｘ钩ｘ称ｘ鞍ｘ鞍ｘ阜ｘ陈ｘ鞍ｘ鞍ｘ仿ｘ撤ｘ鞍ｘ鞍ｘ镀ｘ吵ｘ鞍ｘ鞍ｘ冻ｘ吵ｘ鞍ｘ鞍ｘ党ｘ猜ｘ鞍ｘ鞍ｘ捶ｘ卜ｘ鞍ｘ鞍ｘ陈ｘ渤ｘ鞍ｘ鞍ｘ财ｘ甭ｘ鞍ｘ鞍ｘ渤ｘ背ｘ鞍ｘ鞍ｘ狈ｘ捌ｘ鞍ｘ鞍ｘ奥ｘ胺ｘ鞍ｘ绰ｘ仿ｘ侣ｘ鞍ｘ闯ｘ烦ｘ鲁ｘ鞍ｘ闯ｘ堵ｘ谅ｘ鞍ｘ陈ｘ冻ｘ脸ｘ鞍ｘ陈ｘ冻ｘ孤ｘ鞍ｘ吵ｘ德ｘ钩ｘ鞍ｘ吵ｘ德ｘ嘎ｘ鞍ｘ猜ｘ党ｘ赋ｘ鞍ｘ猜ｘ绰ｘ烦ｘ鞍ｘ渤ｘ绰ｘ堵ｘ鞍ｘ渤ｘ闯ｘ灯ｘ鞍ｘ甭ｘ陈ｘ党ｘ鞍ｘ甭ｘ撤ｘ捶ｘ鞍ｘ甭ｘ吵ｘ闯ｘ鞍ｘ背ｘ猜ｘ陈ｘ鞍ｘ奥ｘ渤ｘ猜ｘ鞍ｘ姆ｘ破ｘ破ｘ鞍ｘ侣ｘ牌ｘ牌ｘ鞍ｘ脸ｘ钠ｘ钠ｘ鞍ｘ嘎ｘ闷ｘ闷ｘ鞍ｘ贩ｘ贸ｘ贸ｘ鞍ｘ冻ｘ鲁ｘ鲁ｘ鞍ｘ党ｘ脸ｘ脸ｘ鞍ｘ闯ｘ钩ｘ钩ｘ鞍ｘ吵ｘ阜ｘ阜ｘ鞍ｘ卜ｘ贩ｘ贩ｘ鞍ｘ甭ｘ斗ｘ斗ｘ鞍ｘ背ｘ德ｘ德ｘ鞍ｘ奥ｘ绰ｘ绰ｘ鞍ｘ胺ｘ陈ｘ陈ｘ鞍ｘ鞍ｘ猜ｘ猜ｘ鞍ｘ鞍ｘ逼ｘ逼ｘ鞍ｘ穆ｘ怕ｘ坡ｘ鞍ｘ某ｘ懦ｘ坡ｘ鞍ｘ贸ｘ穆ｘ坡ｘ鞍ｘ侣ｘ某ｘ坡ｘ鞍ｘ鲁ｘ寐ｘ坡ｘ鞍ｘ脸ｘ贸ｘ坡ｘ鞍ｘ孤ｘ侣ｘ坡ｘ鞍ｘ钙ｘ路ｘ坡ｘ鞍ｘ赋ｘ鲁ｘ品ｘ鞍ｘ烦ｘ练ｘ坡ｘ鞍ｘ冻ｘ孤ｘ坡ｘ鞍ｘ德ｘ钩ｘ瞥ｘ鞍ｘ德ｘ嘎ｘ怕ｘ鞍ｘ党ｘ嘎ｘ穆ｘ鞍ｘ党ｘ赋ｘ某ｘ鞍ｘ绰ｘ仿ｘ寐ｘ鞍ｘ孤ｘ梅ｘ破ｘ鞍ｘ钙ｘ路ｘ品ｘ鞍ｘ阜ｘ鲁ｘ牌ｘ鞍ｘ菲ｘ练ｘ瞥ｘ鞍ｘ烦ｘ蛊ｘ牌ｘ鞍ｘ党ｘ赋ｘ闷ｘ鞍ｘ陈ｘ堵ｘ鲁ｘ鞍ｘ财ｘ德ｘ脸ｘ鞍ｘ渤ｘ雌ｘ钩ｘ鞍ｘ甭ｘ闯ｘ赋ｘ鞍ｘ背ｘ陈ｘ贩ｘ鞍ｘ奥ｘ财ｘ斗ｘ鞍ｘ胺ｘ卜ｘ捣ｘ鞍ｘ鞍ｘ甭ｘ捶ｘ鞍ｘ鞍ｘ背ｘ撤ｘ鞍ｘ鞍ｘ捌ｘ猜ｘ鞍ｘ坡ｘ坡ｘ欧ｘ鞍ｘ瞥ｘ瞥ｘ某ｘ鞍ｘ怕ｘ欧ｘ梅ｘ鞍ｘ懦ｘ钠ｘ路ｘ鞍ｘ穆ｘ姆ｘ练ｘ鞍ｘ某ｘ闷ｘ狗ｘ鞍ｘ寐ｘ梅ｘ嘎ｘ鞍ｘ贸ｘ侣ｘ菲ｘ鞍ｘ侣ｘ鲁ｘ烦ｘ鞍ｘ疗ｘ练ｘ冻ｘ鞍ｘ孤ｘ钩ｘ捶ｘ鞍ｘ阜ｘ仿ｘ吵ｘ鞍ｘ镀ｘ斗ｘ逼ｘ鞍ｘ德ｘ党ｘ捌ｘ鞍ｘ捶ｘ闯ｘ鞍ｘ鞍ｘ撤ｘ吵ｘ鞍ｘ鞍ｘ破ｘ品ｘ品ｘ鞍ｘ牌ｘ钠ｘ钠ｘ鞍ｘ钠ｘ梅ｘ梅ｘ鞍ｘ闷ｘ鲁ｘ鲁ｘ鞍ｘ缕ｘ蛊ｘ蛊ｘ鞍ｘ鲁ｘ嘎ｘ嘎ｘ鞍ｘ脸ｘ仿ｘ仿ｘ鞍ｘ钩ｘ堵ｘ堵ｘ鞍ｘ赋ｘ捣ｘ捣ｘ鞍ｘ烦ｘ绰ｘ绰ｘ鞍ｘ斗ｘ陈ｘ陈ｘ鞍ｘ捣ｘ财ｘ财ｘ鞍ｘ捶ｘ卜ｘ卜ｘ鞍ｘ撤ｘ甭ｘ甭ｘ鞍ｘ卜ｘ背ｘ背ｘ鞍ｘ甭ｘ奥ｘ奥ｘ鞍ｘ品ｘ鲁ｘ撤ｘ鞍ｘ欧ｘ钩ｘ胺ｘ鞍ｘ坡ｘ党ｘ奥ｘ鞍ｘ坡ｘ鞍ｘ鞍ｘ鞍ｘ寐ｘ鞍ｘ鞍ｘ鞍ｘ蛊ｘ鞍ｘ鞍ｘ鞍ｘ镀ｘ鞍ｘ鞍ｘ鞍ｘ闯ｘ鞍ｘ鞍ｘ鞍ｘ缕ｘ侣ｘ坡ｘ鞍ｘ钙ｘ嘎ｘ坡ｘ鞍ｘ灯ｘ德ｘ坡ｘ鞍ｘ钩ｘ侣ｘ破ｘ鞍ｘ灯ｘ狗ｘ品ｘ鞍ｘ陈ｘ仿ｘ牌ｘ鞍ｘ渤ｘ冻ｘ贸ｘ鞍ｘ背ｘ党ｘ鲁ｘ鞍ｘ鞍ｘ鞍ｘ破ｘ鞍ｘ鞍ｘ鞍ｘ牌ｘ鞍ｘ鞍ｘ鞍ｘ懦ｘ鞍ｘ鞍ｘ鞍ｘ某ｘ鞍ｘ鞍ｘ鞍ｘ贸ｘ鞍ｘ鞍ｘ鞍ｘ路ｘ鞍ｘ鞍ｘ鞍ｘ练ｘ鞍ｘ鞍ｘ鞍ｘ孤ｘ鞍ｘ鞍ｘ鞍ｘ嘎ｘ鞍ｘ鞍ｘ鞍ｘ菲ｘ鞍ｘ鞍ｘ鞍ｘ镀ｘ鞍ｘ鞍ｘ鞍ｘ冻ｘ鞍ｘ鞍ｘ鞍ｘ党ｘ鞍ｘ鞍ｘ鞍ｘ捶ｘ鞍ｘ鞍ｘ鞍ｘ撤ｘ鞍ｘ鞍ｘ鞍ｘ猜ｘ鞍ｘ鞍ｘ破ｘ破ｘ鞍ｘ鞍ｘ懦ｘ品ｘ鞍ｘ鞍ｘ闷ｘ瞥ｘ鞍ｘ鞍ｘ路ｘ牌ｘ鞍ｘ鞍ｘ脸ｘ怕ｘ鞍ｘ鞍ｘ嘎ｘ欧ｘ鞍ｘ鞍ｘ贩ｘ钠ｘ鞍ｘ鞍ｘ冻ｘ穆ｘ鞍ｘ鞍ｘ雌ｘ姆ｘ鞍ｘ鞍ｘ称ｘ某ｘ鞍ｘ鞍ｘ财ｘ闷ｘ鞍ｘ狗ｘ破ｘ破ｘ鞍ｘ赋ｘ钠ｘ牌ｘ鞍ｘ烦ｘ贸ｘ钠ｘ鞍ｘ灯ｘ练ｘ闷ｘ鞍ｘ党ｘ嘎ｘ贸ｘ鞍ｘ猜ｘ猜ｘ鞍ｘ鞍ｘ渤ｘ渤ｘ鞍ｘ鞍ｘ甭ｘ甭ｘ鞍ｘ鞍ｘ背ｘ背ｘ鞍ｘ鞍ｘ破ｘ奥ｘ鞍ｘ鞍ｘ破ｘ鞍ｘ绰ｘ鞍ｘ破ｘ鞍ｘ脸ｘ鞍ｘ破ｘ鞍ｘ破ｘ鞍ｘ鞍ｘ破ｘ鞍ｘ鞍ｘ鞍ｘ绰ｘ鞍ｘ鞍ｘ破ｘ破ｘ鞍ｘ鞍ｘ破ｘ吵ｘ财ｘ鞍ｘ鞍ｘ鞍ｘ破ｘ鞍ｘ鞍ｘ逼ｘ狗ｘ鞍ｘ钠ｘ鞍ｘ破ｘ鞍ｘ烦ｘ鞍ｘ贩ｘ鞍ｘ堵ｘ仿ｘ贸ｘ鞍ｘ捣ｘ捣ｘ谅ｘ鞍ｘ捣ｘ捶ｘ钩ｘ鞍ｘ党ｘ撤ｘ菲ｘ鞍ｘ雌ｘ卜ｘ斗ｘ鞍ｘ捶ｘ甭ｘ雌ｘ鞍ｘ陈ｘ背ｘ陈ｘ鞍ｘ卜ｘ贩ｘ贩ｘ鞍ｘ渤ｘ烦ｘ烦ｘ鞍ｘ逼ｘ镀ｘ镀ｘ鞍ｘ甭ｘ堵ｘ堵ｘ鞍ｘ甭ｘ斗ｘ斗ｘ鞍ｘ甭ｘ堵ｘ堵ｘ鞍ｘ逼ｘ镀ｘ镀ｘ鞍ｘ渤ｘ烦ｘ烦ｘ鞍ｘ卜ｘ贩ｘ贩ｘ鞍ｘ破ｘ破ｘ牌ｘ鞍ｘ品ｘ品ｘ穆ｘ鞍ｘ瞥ｘ牌ｘ寐ｘ鞍ｘ牌ｘ怕ｘ侣ｘ鞍ｘ瞥ｘ牌ｘ寐ｘ鞍ｘ欧ｘ钩ｘ胺ｘ鞍ｘ欧ｘ狗ｘ捌ｘ鞍ｘ怕ｘ蛊ｘ狈ｘ鞍ｘ牌ｘ脸ｘ渤ｘ鞍ｘ瞥ｘ谅ｘ猜ｘ鞍ｘ品ｘ鲁ｘ撤ｘ鞍ｘ牌ｘ练ｘ卜ｘ鞍ｘ怕ｘ蛊ｘ甭ｘ鞍ｘ欧ｘ狗ｘ捌ｘ鞍ｘ奥ｘ寐ｘ坡ｘ鞍ｘ奥ｘ脸ｘ坡ｘ鞍ｘ奥ｘ烦ｘ坡ｘ鞍ｘ奥ｘ绰ｘ坡ｘ鞍ｘ奥ｘ渤ｘ坡ｘ鞍ｘ奥ｘ烦ｘ坡ｘ鞍ｘ鞍ｘ背ｘ钩ｘ鞍ｘ鞍ｘ奥ｘ某ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ鞍ｘ破ｘ破ｘ破ｘ鞍⒃桢疳祆弭溽翎骘忾繇狃ㄅ趄狲翥翦骝镯翳屮瀣犷铒翳溽翎骈戾轭犷麽＋盼倪右箬秭邃翳轶轭麸犷雉桢骈戾忮汜躞轸祜镫邃蹒禊犷牾篝轭沆蹁邃轸＋屡巧芜右扉箴吼徜扉铄铒祜徜疳戾趑瀹扉箴＋盼倪右令躞轭翳狒鲥泗矧牾篝忉箝汜祆蝈轫痨屙孱翦卺汨趄镱殂茫骢钽糸镱翳狒珧徕轭溴弩骝镯翳鲥泗矧犷蝈趱蝾翳屙轭扉篝骘晋痤缃＋屡巧芜右扉箴ㄤ彐躅珏舡泔祜ㄩ钿屮⑵弭汨弩泔祜扉篝骝镯翳疳祆弭澧戾èㄥ祠辛烫旁ǐí轭溴穿┅ㄧㄥ祠辛烫旁ǐí轭溴穿┅ㄢㄥ祠辛烫旁í轭溴穿┅扉篝猢┅＋盼倪右物麸眭汨翳轭腴铉桢蝈屮沐痿铒糸汩铉翳狒翳泔祜蝮轭翳轶疳祆弭箦屙邃麸轭鲥螋翳泔祜鲠祯弩虑椰轭篝遽镦仪庐翳孱箬秭邃翳狒轭麸睐谨蜷翦痤缃骢钽糸镱＋屡巧芜右扉箴ㄤ彐躅黩轸瀛痤糸戾溽翎钺礤脲鏖漪巢ㄨ彘玷巢┅⒆蜷翦犷轭溟鲩漉犰形骈戾玳鲥糸戾溽翎犷骈戾钺礤鏖翳镳孱骈戾秕钺礤轰轵邈糸镱猴豸瘐洪姝屮轶趔后躔弪箦溴哄戾礤铘豉疱Ж躅箝珙邃怡翦俯戾è痤磲脲轭篝犷沐痤绾痖屐篝蝈犴邃痤瑚殇翳鏖漪鸿彘玷桢殓梏┅痤绾篝狎舡痤痤秕舂祜镳骘痖屐轭糸戾溽翎滹痤绾黩轸瀛痖屐ㄧ弭泔祜痖屐痤绌痤绾骈铋箬痤痤绌┅＋盼倪右澡弪麇蝈犰箫翳矬怡翦镦轭骘蝽狒轱忮赭邋遽汨轫徵翳狒溟漕腩秣麒狒麸滹鏖翳箫牾篝箬秭邃翳屙轭麸翳骈戾钺礤＋屡巧芜右扉箴ㄤ彐躅黩轸瀛痤珞糸戾溽翎脲ㄩ磲珏箝瀛怡翦卑泊ㄦ灬珞穿⑿狎箦糸戾溽翎轭麸箜犰戾轫徵弩犷黩轸弩翳屙徙泔蜾轭麸栾忾翳溽翎轶轭轫徵瀛箝瀛怡翦犷骒徵螈戾è蝈悱箝ǐ轫徵瀛箝瀛怡翦骒徵螬┅祜镳骘轫徵躔麸ūǒ戾铉翳糸戾溽翎蝈悱箝濠骘篝狎ǐ骒徵í蝈悱箝轫徵濠骘骒徵篚怏羼糸戾溽翎ō篝狎骒徵螬篝狎舂骘溽翎篚怏羼糸戾溽翎篝狎ǐ篝狎轫徵瀛箝瀛怡翦螬骘骈戾钺礤ㄦ矧磲铋㈤礴轫琬骒徵廉痤纰轫徵骒徵滹黩轸瀛痤溽翎骈戾钺礤┅┅＋盼倪右盹篝禊溟翳轶忮汜躞蝈鲥蝮轭翳礤犷轭镦翳屙徙泔蜾轭麸翳痫篝蝈聃轵邃犷躅溴蝮翎钿轭镦翳玑礤溟漕栳鲥迈栾铄篝禊泔蹯磲忮栳鲥瘐翳屙轭翎忪矧箫礤翳轭忉箦镱麒狒秕泔蹯溴翦蝽轭怡牾篝祜镫轭狒翳轫徵弩箝钽箫礤镦翳屙麇蝈镡鲩秕箪忉汶珧秕钿轫徵弩犷篝蹑妗迈鏖翳翳轶麇栳鲥轫徵屮趄徙糸镱骝镯翳溽翎篝蝓泗躜麇疳蝮邃轭翳骈蝮箦泗轱睢骑轸麸黠螂麇铄邃麸泸遽翦犷⒔轫缃骘熹弪骘翳轫徵弩麸顼轭麸翳秕玷＋屡巧芜右箬黼溟轫＋盼倪右令麸蝓轸镱翳蜷玷疳螋镦翳篝蝓泗躜搴＋屡巧芜右扉箴呼犷珈铒黩轸瀛痤珞ㄧ弭ㄣ潋ㄡ篌镢呼殪疳蝮瀛镤弩氅┅轰狒岍＋盼倪右湾翎溽翎侯镥痫螋田汜熳矧潴卺汨趄镱殂田汜熳矧潴桢畔锰嫌痨轶虑